version: '2.1'

services:
  db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: cmsuser
      POSTGRES_PASSWORD: your_password_here

  log:
    build:
      context: ./log
    depends_on:
      - db
  
  cms:
    build:
      context: ./main
    privileged: yes
    depends_on:
      log:
        condition: service_healthy
    ports:
      - 8888:8888
      - 8889:8889
      - 8890:8890
    restart: always
    volumes:
      - ./main/contest:/tmp/contest/