version: '2.1'

services:
  db:
    build:
      context: ./db
    volumes:
      - postgres-db-volume:/data/postgres

  log:
    build:
      context: ./log
    depends_on:
      - db
  
  cms:
    build:
      context: ./main
    privileged: yes
    depends_on:
      log:
        condition: service_healthy
    ports:
      - 8888:8888
      - 8889:8889
      - 8890:8890
    restart: always

volumes:
  postgres-db-volume: